name: CI

on:
  pull_request:
    branches:
        - '*'

jobs:
  stack:
    name: ${{ matrix.os }} / stack / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ["2.11.1"]
        ghc: ["8.8.4", "8.10.7", "9.2.8", "9.4.5", "nightly"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: jobs_test
          POSTGRES_USER: jobs_test
          POSTGRES_DB: jobs_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: confirm that postgres is working
      run: |
        PGPASSWORD=jobs_test psql -U jobs_test -h localhost -c 'select 1'

    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        enable-stack: true
        stack-no-global: true
        stack-setup-ghc: true
        stack-version: ${{ matrix.stack }}
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --stack-yaml=ghc-${{ matrix.ghc }}.stack.yaml

    - name: Test
      run: |
        stack test --stack-yaml=ghc-${{ matrix.ghc }}.stack.yaml
